### ISSUE TITLE
Name all EasyOChem Plugins with an identical prefix

### ISSUE THREAD

**Issue by Kathrin84** [cleblond/moodle-qtype_easyoselectjs#1]
At the moment, when adding a question to a quiz, the question types are sorted by name and not by category and name or something else.
This leads to the situation that the chemistry question types are not close together and the user has to search through the list.

With an identical prefix, all of chemistry question types would be listed all together in a block kind of way.
This would make it easier for the user to find the chemistry related question types. 

I place this request only as one issue but it stands representative for your other chemistry question types in Moodle.

**Comment by abias** [comment]
As this change has been integrated, this issue could be closed, right?
