### ISSUE TITLE
Place chemaxon logo within the plugin

### ISSUE THREAD

**Issue by Kathrin84** [cleblond/moodle-qtype_easyoselectjs#2]
Hi,

I would like to use your plugin. It requires MarvinJS.
So I asked for a license from ChemAxon and I got it, as we fulfill their requirements. They said that we should place their logo on our website and link to their website.

Would it be possible to integrate this logo (with optional visibilty) directly within your plugin as all users of your plugins have to deal with this requirement from ChemAxon.

Kind regards
Kathrin

**Comment by abias** [comment]
As this change has been integrated, this issue could be closed, right?
